### ISSUE TITLE
Can this be put on nuget.org?

### ISSUE THREAD

**Issue by spybug** [kirtisagar/XamarinFormsRadioButtonXAML#5]
I was wondering if you could put this in a nuget package and have it on nuget.org to make installation easier on Visual Studio?

**Comment by kirtisagar** [comment]
thanks for writing, this control is part of XLabs already on nuget: 
https://github.com/XLabs/Xamarin-Forms-Labs
https://www.nuget.org/packages/XLabs.Forms/
