### ISSUE TITLE
iOS Radio Button Text Overlapping

### ISSUE THREAD

**Issue by ravinderjangra** [kirtisagar/XamarinFormsRadioButtonXAML#8]
Radio Button Text is overlapping in ios

**Comment by ravinderjangra** [comment]
Radio Button Text is overlapping.

**Comment by ravinderjangra** [comment]
help me with issue.

**Comment by kirtisagar** [comment]
this is part of XLabs now  https://github.com/XLabs/Xamarin-Forms-Labs
